feat: add utility paleet
Fair-Squares/fair-squares pull request #131
Opened 2022-08-31 12:27 UTC by cuteolaf

2022-08-31 23:58 UTC, ndkazu approved these changes

2022-09-01 01:26 UTC, ndkazu requested changes

2022-09-01 01:26 UTC, ndkazu commented on runtime/Cargo.toml
>  	"pallet-onboarding/try-runtime",
Is there a reason for not adding `"pallet-utility/try-runtime"` here?
and there is also the missing `"pallet-utility/runtime-benchmarks"` in the `runtime-benchmark` section.
Usually I refer to the following Files/folder to add pallets:
https://github.com/paritytech/substrate/blob/polkadot-v0.9.26/bin/node/runtime/Cargo.toml

2022-09-01 01:26 UTC, ndkazu commented on runtime/src/lib.rs
>  );
Here also, missing `[pallet_utility, Utility]` in the `define_benchmark` section.

2022-09-01 08:55 UTC, letodunc commented
To prevent missing things when adding a new pallet, there is a script that automatize it for you. It's **_add_new_pallet.sh_** in the scripts folder. You execute it from the root folder of the project. In your case, a use could be _**scripts/add_new_pallet.sh utility Utility**_. Everything will be correctly configured for the basic add in the project. Then you can customize it with what you need.

2022-09-01 09:33 UTC, ilhanu commented
No sure why the coverage tests are failing, might have to do with the that it's an external PR

2022-09-04 18:45 UTC, ilhanu commented
@cuteolaf can you please check the logs for the benchmarking and provide a fix.

2022-09-05 01:05 UTC, ndkazu commented
A few things I do before sending a commit:
- `cargo check` to make sure that it compiles
- `cargo test` to be sure that all the tests are correctly configured and pass.
- `cargo build --release --features runtime-benchmarks` to be sure that all the benchmarks are correctly configured and pass.
sometimes ou will also have additionnal tests in your benchmarks (it is the case for some FairSquares pallets), in this case you also want to run the following:
- `cargo test --features runtime-benchmarks`

In my eperience, If all the checks above pass on your local node, your commit will checkout without ANY problem.

2022-09-05 22:01 UTC, merged