Updated Onboarding
Fair-Squares/fair-squares pull request #134
Opened 2022-09-08 13:09 UTC by ndkazu

In this first step, tests are disabled, and will be upgraded next.
Assets status name have been updated, and a new call which changes status after positive investor's vote has been added

2022-09-08 14:46 UTC, letodunc requested changes

2022-09-08 14:46 UTC, letodunc commented on pallets/onboarding/src/types.rs
> +	ONBOARDED,
There should be some test update for these changes. It looks like there is no test coverage on them

2022-09-08 15:02 UTC, letodunc commented on pallets/onboarding/src/types.rs
> +	ONBOARDED,
I just reviewed the issue commentary about the tests. Why not updating the tests in this issue?
Those changes seem to be those to be done in issue [129](https://github.com/Fair-Squares/fair-squares/issues/129). Is this issue merged with the current one?

2022-09-09 08:39 UTC, ilhanu approved these changes

2022-09-09 08:39 UTC, ilhanu commented on pallets/onboarding/src/lib.rs
> +			ensure!(status == AssetStatus::FINALIZED, Error::<T>::VoteNedeed);
This status change is the final change that a house in an acquisition flow acquires. Should it not check before that the OFFERED status is currently the case ?

2022-09-09 10:33 UTC, ndkazu commented on pallets/onboarding/src/lib.rs
> +			ensure!(status == AssetStatus::FINALIZED, Error::<T>::VoteNedeed);
This line is in the `do_buy` function which execute the final transaction. At this point of the workflow, the asset has been already `Finalized` by the notary.

2022-09-09 15:27 UTC, letodunc approved these changes

2022-09-10 09:22 UTC, merged