166 bidding pallet execute bidding workflow periodically
Fair-Squares/fair-squares pull request #167
Opened 2022-09-26 09:07 UTC by letodunc

Added periodic call to the bidding pallet
- Added `BiddingExecutionPeriod` in Bidding config pallet
- Added hook to call each `BiddingExecutionPeriod` the bidding workflow

2022-09-26 10:54 UTC, ilhanu requested changes
- When bidding-pallet begins, we want to have these periodic events to be published. A good event name would be `NewAssetScanPeriod`
For the rest looking good and happy to test it further once merged into main

2022-09-26 10:54 UTC, ilhanu commented on pallets/bidding/src/lib.rs
>  		NoNewHousesFound,
This doesn't belong here. If there are no new houses it should not emit an Error, but just an event is fine

2022-09-26 10:54 UTC, ilhanu commented on pallets/bidding/src/lib.rs
> +
How does this exactly work? 
The hook checks every block if it's time to starting the Bidding ?

2022-09-26 10:54 UTC, ilhanu commented on runtime/src/lib.rs
> +	pub const BiddingExecutionPeriod: u32 = EPOCH_DURATION_IN_BLOCKS;
```suggestion
	pub const NewAssetScanPeriod: u32 = EPOCH_DURATION_IN_BLOCKS;
```

2022-09-26 10:54 UTC, ilhanu commented on pallets/bidding/src/lib.rs
> +		type BiddingExecutionPeriod: Get<Self::BlockNumber>;
```suggestion
		type NewAssetScanPeriod: Get<Self::BlockNumber>;
```

2022-09-26 10:54 UTC, ilhanu commented on runtime/src/lib.rs
> +	type BiddingExecutionPeriod = BiddingExecutionPeriod;
```suggestion
	type NewAssetScanPeriod = NewAssetScanPeriod;
```

2022-09-26 14:25 UTC, letodunc commented on pallets/bidding/src/lib.rs
> +
It checks every block if an epoch has finished to launch the process.

2022-09-27 11:54 UTC, ilhanu commented
@letodunc can we test that the hook works as intended ? 

- New session should start the hook
- The hook should make the bidding pallet scan

2022-09-27 13:09 UTC, ndkazu approved these changes

2022-09-27 16:50 UTC, letodunc commented
> Please before accepting we need the test for the hook transition

I propose to do the test in a second step. For simpliciy, let's merge the #168 and this PR in main as there are changes in #168 impacting #166. The new PR will contains test on periodic call.

2022-09-28 06:34 UTC, merged