168 bidding pallet improvment of bidding workflow
Fair-Squares/fair-squares pull request #171
Opened 2022-09-27 08:15 UTC by letodunc

Improved the bidding mechanism
Updated the tests accordingly

2022-09-27 14:33 UTC, ilhanu requested changes
The pallet is far from ready looking at it. It completes what we want to do in a happy flow. 

I'm missing a test on the use of the traits and tied to emitting events :
```
		type SimultaneousAssetBidder: Get<u64>;
		type MaxTriesBid: Get<u64>;
		type MaxTriesAseemblingInvestor: Get<u64>;
		type MaximumSharePerInvestor: Get<u64>;
		type MinimumSharePerInvestor: Get<u64>;
```

What is the difference between these [two](https://github.com/Fair-Squares/fair-squares/blob/9467b7d4cb269a4c29a21ad04271dc7dea5812d0/pallets/bidding/src/lib.rs#L58-L59) traits ?

2022-09-27 14:33 UTC, ilhanu commented on pallets/bidding/src/lib.rs
> +		elligible_contributions: Vec<(Housing_Fund::AccountIdOf<T>, Housing_Fund::BalanceOf<T>, Housing_Fund::BalanceOf<T>)>,
```suggestion
		eligible_contributions: Vec<(Housing_Fund::AccountIdOf<T>, Housing_Fund::BalanceOf<T>, Housing_Fund::BalanceOf<T>)>,
```

2022-09-27 14:33 UTC, ilhanu commented on pallets/bidding/src/tests.rs
> +fn create_investor_list_fourth_case_should_succeed() {
What is meant by these test names ?

2022-09-27 14:36 UTC, letodunc commented
> The pallet is far from ready looking at it. It completes what we want to do in a happy flow.
> 
> I'm missing a test on the use of the traits and tied to emitting events :
> 
> ```
> 		type SimultaneousAssetBidder: Get<u64>;
> 		type MaxTriesBid: Get<u64>;
> 		type MaxTriesAseemblingInvestor: Get<u64>;
> 		type MaximumSharePerInvestor: Get<u64>;
> 		type MinimumSharePerInvestor: Get<u64>;
> ```
> 
> What is the difference between these [two](https://github.com/Fair-Squares/fair-squares/blob/9467b7d4cb269a4c29a21ad04271dc7dea5812d0/pallets/bidding/src/lib.rs#L58-L59) traits ?

2022-09-27 14:39 UTC, letodunc commented on pallets/bidding/src/lib.rs
>  	pub enum Event<T: Config> {
It was to manage Asset already in the workflow process. It is managed with the `FINALISING` status. So the event is not needed anymore.

2022-09-27 14:42 UTC, letodunc commented on pallets/bidding/src/lib.rs
>  	pub enum Event<T: Config> {
It is actually to differentiate the tries to make a bid with the Housing Fund and the tries to assemble the investor.

2022-09-27 14:48 UTC, letodunc commented on pallets/bidding/src/tests.rs
> +fn create_investor_list_fourth_case_should_succeed() {
Different configurations are used to set the test. The waited result is a success in this case and its the fourth case to test the `creator_investor_list()` function.

2022-09-27 19:05 UTC, ilhanu commented on pallets/bidding/src/lib.rs
>  	pub enum Event<T: Config> {
Ok we can remove it, also once a house is selected by the bidding pallet it would have a status of its own, so this event is indeed unnecessary.

2022-09-27 19:06 UTC, ilhanu approved these changes

2022-09-28 01:27 UTC, ndkazu approved these changes
Considering the amount of code lines, I think a more detailed in-code documentation is needed.
This will also greatly help streamline the reviews made by the Web3 fundation.

2022-09-28 08:22 UTC, merged