add pallet_identity to the runtime
Fair-Squares/fair-squares pull request #211
Opened 2022-11-16 13:47 UTC by cuteolaf

2022-11-16 23:05 UTC, ilhanu commented on node/src/chain_spec.rs
> +			],
Can we please pick someone else, as these keys already have a role to play in council etc. 
You can add new keys to the chain and give them a balance.

2022-11-16 23:21 UTC, ilhanu requested changes
small changes and let's keep small fixes away from PR for what they are intended for.

2022-11-16 23:21 UTC, ilhanu commented on runtime/src/lib.rs
> +pub use pallet_share_distributor;
structure is good 🔢

2022-11-16 23:21 UTC, ilhanu commented on runtime/src/lib.rs
> +	pub const MaxRegistrars: u32 = 20;
```suggestion
	pub const BasicDeposit: Balance = deposit(1, 258); // 258 bytes on-chain
	pub const FieldDeposit: Balance = deposit(0, 66); // 66 bytes on-chain
	pub const SubAccountDeposit: Balance = deposit(1, 53);
	pub const MaxAdditionalFields: u32 = 100;
	pub const MaxRegistrars: u32 = 1;
```
not sure about the despitfees per bytes how to read this ?

2022-11-16 23:21 UTC, ilhanu commented on pallets/bidding/src/tests.rs
> +		let event = events.pop().expect("Expected at least one EventRecord to be found").event;
What does this change have to do with the identity pallet ?

2022-11-17 07:27 UTC, cuteolaf commented on runtime/src/lib.rs
> +	pub const MaxRegistrars: u32 = 20;
I saw two example configurations.

https://github.com/paritytech/substrate/blob/a7ba55d3c54b9957c242f659e02f5b5a0f47b3ff/bin/node/runtime/src/lib.rs#L1312-L1314

https://github.com/PureStake/moonbeam/blob/2be5c91596e6a5920aabb587a24fa86b55c9cfd2/runtime/moonbeam/src/lib.rs#L653-L657

They look similar but I'm not sure what's the main difference. Still thinking about it.

2022-11-17 07:28 UTC, cuteolaf commented on pallets/bidding/src/tests.rs
> +		let event = events.pop().expect("Expected at least one EventRecord to be found").event;
Nothing. Just a formatting problem.

2022-11-17 13:19 UTC, ilhanu reviewed
Regarding setting the identities, can you check [this](https://github.com/paritytech/substrate/blob/8161ee1aa1ccd122150e40a8aef23df3d0a16d02/frame/support/src/traits/hooks.rs#L108-L119) 

Apparently we can set stuff with frame trait `on_genesis` think this will be a root call.

2022-11-17 13:19 UTC, ilhanu commented on node/src/chain_spec.rs
> +				AccountId32::from_str("5FFDJcwqRCFPFKM44DhFC3ituGwgaQKxpp75Ger9xNs3GCiU").unwrap(),
Which accounts are these ?

2022-11-17 13:19 UTC, ilhanu commented on runtime/src/lib.rs
> +	pub const FieldDeposit: Balance = deposit(0, 66); // 66 bytes on-chain
I think these can be stated as [contants](https://github.com/Fair-Squares/fair-squares/blob/main/runtime/src/constants.rs#L24-L26) as the ParityTech example you linked to us

2022-11-17 13:28 UTC, cuteolaf commented on node/src/chain_spec.rs
> +				AccountId32::from_str("5FFDJcwqRCFPFKM44DhFC3ituGwgaQKxpp75Ger9xNs3GCiU").unwrap(),
Random accounts generated by subkey

2022-11-17 13:34 UTC, cuteolaf commented on runtime/src/lib.rs
> +	pub const FieldDeposit: Balance = deposit(0, 66); // 66 bytes on-chain
updated

2022-11-17 14:45 UTC, letodunc requested changes

2022-11-17 14:45 UTC, letodunc commented on node/src/chain_spec.rs
> +				AccountId32::from_str("5FFDJcwqRCFPFKM44DhFC3ituGwgaQKxpp75Ger9xNs3GCiU").unwrap(),
Use `get_account_id_from_seed` to use named accounts. Those representatives will be selected in the workflow later.

2022-11-17 14:59 UTC, letodunc approved these changes

2022-11-17 22:34 UTC, ilhanu approved these changes
Looks good, thanks for correcting some of the reviewed parts. Got that you don't want to implement the on-genesis implementation in this PR. It's still worth looking into it will just save us a lot of work to have  a genesis config of that.

2022-11-18 14:01 UTC, ndkazu approved these changes

2022-11-18 14:25 UTC, merged