Propose a tenant
Fair-Squares/fair-squares pull request #218
Opened 2022-11-24 15:43 UTC by cuteolaf

2022-11-25 04:24 UTC, ndkazu requested changes

2022-11-25 04:24 UTC, ndkazu commented on pallets/asset_management/src/functions.rs
> +		Roles::TenantLog::<T>::insert(&tenant, tenant0);
this part is doing the same thing as the `set_role` function in `pallet_role`. But the `set_role` function has to be a SERVICER. we could do the following:
1) Give the SERVICER role to the virtual account at virtual account creation in `share_distributor` ->function.rs->`fn virtual_account`.
2) Use  
`pallet_roles::Pallet::<T>::set_role(origin_virtual,&tenant,pallet_roles::Accounts::TENANT)`
 instead

2022-11-25 04:24 UTC, ndkazu commented on pallets/asset_management/src/functions.rs
> +
Here (Case of 1 asset<-->several tenants), we need to mutate the storage value, and push the tenant account in the tenant Vector (see my other comment about tenant field in Asset struct) instead of inserting a new one.

2022-11-25 04:24 UTC, ndkazu commented on pallets/asset_management/src/lib.rs
> +			// Ensure that the asset is not linked with a tenant
This check might change, because of the 1 asset<--> several tenants rule

2022-11-25 04:36 UTC, ndkazu reviewed
It also important to remember that the Representative will also do spending proposals, or Tenant_eviction proposals. 
so instead of `fn propose_tenant` which is specific to one proposal, I suggest `fn Representative_proposals`, and for the general inner structure,  see the function `launch_representative_session` from line 252, together with the file types.rs-line41

2022-11-25 09:19 UTC, letodunc approved these changes
With the requested changes done, it's good for me.

2022-11-25 12:39 UTC, ndkazu commented on pallets/asset_management/src/functions.rs
> +		Roles::TenantLog::<T>::insert(&tenant, tenant0);
Ok sorry Oliver, I think I am wrong on this one: You are only updating the infos of an existing Tenant. Forget about this one....

2022-11-26 01:53 UTC, ndkazu approved these changes

2022-11-26 09:44 UTC, merged