Update lib.rs
Fair-Squares/fair-squares pull request #43
Opened 2022-06-13 16:00 UTC by ndkazu

In the pallet roles:
- Added descriptive Events and Errors for the different role/account creation
- Added a Seller/Servicer account creation rejection function for the admin
- Added descriptives events in Account_creation approval & rejection functions
- Added additional check in Account_creation approval & rejection functions (caller account is not account to be verified)

2022-06-13 20:49 UTC, ilhanu commented on pallets/roles/src/lib.rs
> +		CreationRequestCreated(<T as frame_system::Config>::BlockNumber,<T as frame_system::Config>::AccountId),
Why are the Events typed as selected? If they are a part of the `frame_system` and `	#[pallet::config]` can they not be typed as as following 

example: `		InvestorCreated(blocknumber T::BlockNumber, accountId T::AccountId)`

2022-06-13 20:59 UTC, ilhanu commented on pallets/roles/src/lib.rs
> +         Ok(().into())
Nice addition 👍🏼 

We can also give the role a name like a [membership-manager](https://github.com/paritytech/substrate/blob/bc310fdd1040af8a3d2901b5d6f4cf8d5250aeb7/frame/alliance/src/lib.rs#L238-L239)

2022-06-13 21:08 UTC, ilhanu requested changes
Thanks a lot for the work, it looks really neat! I'm at the moment heavily inspired by the alliance pallet as you can read in the review, it has bits of similar work and nice coding styles. We don't necessarily need to adhere to those standards, however it will make our code easier readable and future-proof.

Also it would be nice if we could make every PR standard especially when adding features that we also add tests to it. @MrishoLukamba was working on it in the #40, not sure what the plan is with that PR, but it would be nice before merging this that we have some basic unit tests that can test these functions.

2022-06-14 00:39 UTC, ndkazu commented on pallets/roles/src/lib.rs
> +		CreationRequestCreated(<T as frame_system::Config>::BlockNumber,<T as frame_system::Config>::AccountId),
You're totally right. I blindly mimicked the parity node-template syntax, but it's really heavy.

2022-06-15 14:16 UTC, MrishoLukamba commented
done the testing on main

2022-06-15 14:47 UTC, letodunc approved these changes

2022-06-15 19:39 UTC, ilhanu commented on pallets/roles/src/lib.rs
> +		CreationRequestCreated(T::BlockNumber,T::AccountId),
Sweet!

2022-06-15 19:41 UTC, ilhanu commented on pallets/roles/src/lib.rs
> +	}
Yeah this is a good start for the mananager or the verifier we called as in the issue #36

2022-06-15 19:49 UTC, ilhanu approved these changes
Thanks for the improvements, the last two commits could have also been handled with the following syntax
```
git checkout main
git merge origin/37_housing_fund (example) 
```
It make it much more understandable where the code comes from. You can squash and merge it.

2022-06-15 23:47 UTC, merged