tested few cases
Fair-Squares/fair-squares pull request #47
Opened 2022-06-15 13:43 UTC by MrishoLukamba

Tested some functions and edge cases works fine , The error messages are not friendly yet.

2022-06-15 20:42 UTC, ilhanu commented on pallets/roles/src/tests.rs
> +			Error::<Test>::NoneValue
Hey Mrisho, thanks for being the only one testing 😅 You are early as the functionality is just being added.

It would be nice if the test fails it reports the error in the pallet

Please see the remainder of the tests:
- [x]  Getting roles, successful
- [ ]  Getting several roles, unsuccessful  **This needs more extensive testing.**
- [ ]  Getting role (seller, servicer) without verification, unsuccessful

These are just examples you are also welcome to code your own test you think that are valuable.

2022-06-15 20:48 UTC, ilhanu requested changes
Thanks for adding some tests, the PR is bit early, but some early tests help to further kickstart it. The branch is not checking though, try to merge stuff after the merge of Kazu's branch within your own branch. It will most likely fix it.

2022-06-15 23:25 UTC, MrishoLukamba commented on pallets/roles/src/structs.rs
> +    pub age:T::BlockNumber,
No it doesn't bring conflicts. So the type aliases was not needed as all associated types were on config trait. And i think code consistency is good

2022-06-15 23:26 UTC, MrishoLukamba commented on pallets/roles/src/tests.rs
> +			Error::<Test>::NoneValue
Okey

2022-06-15 23:26 UTC, MrishoLukamba commented on .idea/vcs.xml
> +</project>
Will do

2022-06-15 23:28 UTC, MrishoLukamba commented
So i should wait clone the kazu branch repo and do testing and he will submit as a whole tested branch ryt

2022-06-16 01:10 UTC, ndkazu reviewed
The roles pallet has been finalized and merged in main. This is creating some conflicts in your PR, and we should discuss as a team about the way to deal with this (merge pull?).

2022-06-25 15:55 UTC, closed without merging